export const GENERATING_MODEL = "GENERATING_MODEL"
export const DESIGN_PROPS_SUCCESS = "DESIGN_PROPS_SUCCESS"
export const MODEL_GENERATED = "MODEL_GENERATED"


export const REQUEST_DESIGNS= "REQUEST_DESIGNS"
export const REQUEST_DESIGN_FAILED = "REQUEST_DESIGN_FAILED"
export const REQUEST_DESIGN_SUCCESS = "REQUEST_DESIGN_SUCCESS"











